sudo: required
dist: trusty
language: python
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev libboost-system-dev libboost-thread-dev libboost-filesystem-dev libboost-test-dev libboost-coroutine-dev libboost-context-dev libboost-program-options-dev libboost-regex-dev
  - sudo apt-get install -y libapr1-dev libaprutil1-dev libaprutil1-dbd-sqlite3
  - sudo apt-get install -y liblog4cxx10-dev liblog4cxx10
  - sudo apt-get install -y libjemalloc-dev
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libmicrohttpd-dev
  - sudo apt-get install -y cmake


before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j4
  - ctest -VV
  - functests/storage_test /tmp
  - akumulid/akumulid --init
  - python functests/test_data_ingestion.py akumulid/ TCP
  - python functests/test_data_ingestion.py akumulid/ UDP
  - python functests/test_query_language.py akumulid/
  #- python functests/test_continuous_queries.py akumulid/
  - python functests/test_volume_overflow.py akumulid/
  - python functests/test_restart.py akumulid/
  - python functests/test_kill.py akumulid/
  - python functests/test_concurrency.py akumulid/

after_script:
  - cp /tmp/akumuli.log shippable/testresults
